ktor:
  application:
    modules:
      - com.example.ApplicationKt.mainModule
  deployment:
    port: 8080
aws:
  region: ${APP_REGION:ap-southeast-2}
#  endpoint: ${AWS_ENDPOINT:http://localhost:8000}
  tableName: ${AWS_TABLE_NAME:quotes}