ktor:
  application:
    modules:
      - com.example.ApplicationKt.mainModule
  deployment:
    port: 8080
aws:
  region: ${AWS_REGION:"us-east-1"}
  endpoint: ${AWS_ENDPOINT:"http://localhost:8000"}
  tableName: ${AWS_TABLE_NAME:"quotes"}